### ISSUE TITLE
Improve this by defining the identity table as class variable 

### ISSUE THREAD

**Issue by chaosAD** [usagitoneko97/klara#1]
https://github.com/usagitoneko97/python-ast/blob/78330cbc3d4601160175f5073a6630a157fce6db/A3.LVN/lvn.py#L30

Unlike the above, a class variable is instantiated only once when the class is created.

The following shows how to define it as class variable.
```python
class Lvn:
    identity_expr = {(None, '*', 2):(None, '+', None), (None, '+', 0):('0', '+', None), .....}

    # Accessing the table is a bit tricky though since you need this class' handle to access it.
    # To get the current class, use type(self) as shown below.
    def get_alternate_id(self, id):
        return type(self).identity_expr.get(id)
````

**Comment by pfalcon** [comment]
>  return type(self).identity_expr.get(id)

Another way:

~~~
self.__class__.identity_expr.get(id)
~~~

But in all fairness, you can do just:

~~~
self.identity_expr.get(id)
~~~

Because Python lookup rules say that an attribute is first looked up in an instance, then if not found, in class (then in base classes in MRO order).

Except if you look up in class right away, a Python compiler would be able to generate more efficient code. So, please write code for (future) Python compilers, or all this SSA stuff will be in vain ;-).

**Comment by usagitoneko97** [comment]
Close since LVN is removed
